### ISSUE TITLE
Extra buttons cause text overlaps

### ISSUE THREAD

**Issue by Fevix** [peterellisjones/Railroader-SmartOrders#7]
When extra buttons appear in the AI tabs (EG., "Pass Fusee", "Pass Signal"), the text is moved up but the window is not resized, which leads to the "Car // Equipment // Operations // Orders" line overlapping the equipment type. 
![image](https://github.com/user-attachments/assets/f04a8afd-c8e0-4d71-a0c8-bc1d425a1b54)

(This is NOT an issue with the other mod that adds shunting to the Road menu, as there's room for the lower text to shift up)

**Comment by peterellisjones** [comment]
Hi @Fevix thanks for reporting the bug, it's now fixed in v1.2.0 https://github.com/peterellisjones/Railroader-SmartOrders/releases/tag/v1.2.0
